FROM ubuntu:latest
RUN apt-get update && apt-get upgrade && apt-get install git sqlite3 nmap python3-pip -y
RUN python3 -m pip install python-dotenv
RUN python3 -m pip install crontab
RUN python3 -m pip install lxml  
RUN python3 -m pip install Django
RUN git clone https://github.com/lnfjobs/rainmap-lite
WORKDIR /rainmap-lite/rainmap-lite/ 
ADD  run.sh /rainmap-lite/rainmap-lite/run.sh
RUN chmod 777 /rainmap-lite/rainmap-lite/run.sh
ENTRYPOINT ["bash", "/run.sh"] 
