FROM ubuntu:latest
RUN apt-get update && apt-get install sqlite3 git nmap python3-pip  -y
RUN python3 -m pip install -U pip
RUN python3 -m pip install lxml
RUN python3 -m pip install Django
RUN git clone https://github.com/lnfjobs/rainmap-lite
ENTRYPOINT ["bash", "/startup.sh"]
